# Generated by Django 4.1.4 on 2022-12-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monument_name', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('contact_number', models.BigIntegerField()),
                ('charges', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], max_length=6)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('debit card', 'Debit Card'), ('credit card', 'Credit Card'), ('bank transfer', 'Bank Transfer')], max_length=15)),
                ('receipt_id', models.IntegerField()),
                ('monument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('monument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='files')),
                ('audio_language', models.CharField(choices=[('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi')], max_length=10)),
                ('monument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument')),
            ],
        ),
    ]
