# Generated by Django 4.1 on 2023-02-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='cityid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.city'),
        ),
    ]
