# Generated by Django 4.1.3 on 2023-02-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0004_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propic',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
