# Generated by Django 4.1.3 on 2023-02-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0005_user_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
