# Generated by Django 4.1.3 on 2023-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0007_alter_feedback_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='popular_place',
            field=models.ImageField(null=True, upload_to='city'),
        ),
    ]
