# Generated by Django 4.1.3 on 2023-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0008_city_popular_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(null=True, upload_to='commentusers'),
        ),
    ]
