# Generated by Django 4.1.3 on 2023-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0009_alter_feedback_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='monument',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='contact_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='days',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='language',
            field=models.CharField(choices=[('engish', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='map_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='timing',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_language',
            field=models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
