# Generated by Django 4.1.3 on 2023-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0011_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='info',
        ),
        migrations.AddField(
            model_name='audio',
            name='file_path_eng',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='audio',
            name='file_path_guj',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='audio',
            name='file_path_hindi',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='monument',
            name='info_eng',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='info_guj',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='info_hindi',
            field=models.TextField(null=True),
        ),
    ]
