# Generated by Django 4.1.3 on 2023-03-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0013_remove_audio_audio_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='language',
        ),
    ]
