# Generated by Django 4.1.3 on 2023-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0014_remove_monument_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='name_guj',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='name_hindi',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
