# Generated by Django 4.1.3 on 2023-03-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0015_monument_name_guj_monument_name_hindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='address_guj',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='address_hindi',
            field=models.TextField(null=True),
        ),
    ]
