# Generated by Django 4.1.3 on 2023-03-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0019_monument_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='photo',
        ),
    ]
