# Generated by Django 4.1.3 on 2023-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0020_remove_monument_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.DeleteModel(
            name='monument_photos',
        ),
    ]
