# Generated by Django 4.1.3 on 2023-03-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0021_monument_photo_delete_monument_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='monument_id',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='monument_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='cityid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='monument_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='audio',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='city',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='monument',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
