# Generated by Django 4.1.3 on 2023-03-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0023_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monument_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='monument photos')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument')),
            ],
        ),
    ]
