# Generated by Django 4.1.3 on 2023-03-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0025_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guide',
        ),
    ]
