# Generated by Django 4.1.3 on 2023-03-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0026_delete_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('date_time', models.DateTimeField()),
                ('monument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.user')),
            ],
        ),
    ]
