# Generated by Django 4.1.3 on 2023-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0027_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='charges',
            field=models.IntegerField(null=True),
        ),
    ]
