# Generated by Django 4.1.3 on 2023-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0028_guide_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='date_time',
        ),
        migrations.AddField(
            model_name='guide',
            name='booked_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_time',
            field=models.TimeField(null=True),
        ),
    ]
