# Generated by Django 4.1.3 on 2023-03-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0029_remove_guide_date_time_guide_booked_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='charges',
        ),
    ]
