# Generated by Django 4.1.3 on 2023-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0031_remove_guide_guide_date_remove_guide_guide_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='charges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_time',
            field=models.TimeField(null=True),
        ),
    ]
