# Generated by Django 4.1.3 on 2023-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0033_rename_guide_time_guide_end_time_guide_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='monument_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
