# Generated by Django 4.1.3 on 2023-03-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0034_remove_payment_monument_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
