# Generated by Django 4.1.3 on 2023-03-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0035_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('debit card', 'Debit Card'), ('credit card', 'Credit Card'), ('bank transfer', 'Bank Transfer')], max_length=15)),
                ('receipt_id', models.IntegerField()),
                ('monument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.user')),
            ],
        ),
    ]
