# Generated by Django 4.1.3 on 2023-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0036_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='monument_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
