# Generated by Django 4.1.3 on 2023-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0039_remove_user_dob_remove_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booked_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='charges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='guide_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='guide',
        ),
    ]
