# Generated by Django 4.1.3 on 2023-03-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0040_payment_booked_time_payment_charges_payment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='monument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument', unique=True),
        ),
    ]
