# Generated by Django 4.1.3 on 2023-03-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0041_alter_audio_monument_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_path_eng',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_path_guj',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_path_hindi',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
