# Generated by Django 4.1 on 2023-03-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0042_alter_audio_file_path_eng_alter_audio_file_path_guj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='file_path_eng',
            new_name='file_path_english',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='file_path_guj',
            new_name='file_path_gujarati',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='monument_id',
            new_name='monument_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='monument_id',
            new_name='monument_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='address_guj',
            new_name='address_Gujarati',
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='cityid',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='info_eng',
            new_name='info_english',
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='info_guj',
            new_name='info_gujarati',
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='name_guj',
            new_name='name_gujarati',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='monument_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='monument_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audioguideapp.monument'),
        ),
    ]
