# Generated by Django 4.1 on 2023-03-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0044_rename_info_hindi_monument_info_hindi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='guide_name',
        ),
    ]
