# Generated by Django 4.1 on 2023-03-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0045_rename_name_payment_guide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.ImageField(default='none', null=True, upload_to='users'),
        ),
    ]
