# Generated by Django 4.1.3 on 2023-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0047_alter_user_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.ImageField(default='images/resource/default-user.png', null=True, upload_to='users'),
        ),
    ]
