# Generated by Django 5.0.2 on 2024-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0048_alter_user_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
