# Generated by Django 5.0.2 on 2024-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0049_alter_user_propic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='citys',
        ),
    ]
